### ISSUE TITLE
关于全面屏的底部标示

### ISSUE THREAD

**Issue by zizikoth** [linwg1988/imagebrowser#1]
可以进行判断 如果是底部有虚拟导航栏的 就重新设置padding
if(BarUtils.isNavBarVisible(getActivity())) {
            circlePageIndicator.setPadding(0, 0, 0, BarUtils.getNavBarHeight());
}

**Comment by linwg1988** [comment]
谢谢建议，因为时间关系，且每个人对底部导航栏判断方法有所不同，这里仅提供这只底部指示器内间隙的方法来调整UI，版本1.1.4提供.
